# Generated by Django 4.2.3 on 2023-08-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecognizedWord',
        ),
    ]
